# Copyright (c) 2026, Avunu LLC and contributors
# For license information, please see license.txt

"""Shell for the customer project portal SPA (``/projects`` and ``/projects/*``).

``projects.html`` is generated by ``yarn build:portal`` (see
``vite.portal.config.ts``); the frappe-ui build plugin injects every key of
``context.boot`` into ``window`` (so ``window.csrf_token`` reaches
``frappeRequest``).  Because Frappe resolves pages over the installed apps in
reverse install order, this page also takes over ERPNext's legacy
``/projects?project=X`` page — those links are redirected into the SPA.
"""

from urllib.parse import quote, urlencode

import frappe
from frappe.core.doctype.navbar_settings.navbar_settings import get_app_logo
from frappe.website.utils import get_portal_sidebar_items

from erpnext_taskview.portal.access import is_staff

no_cache = 1

# Portal menu routes the SPA itself replaces.
_OWN_ROUTES = {"/project", "/projects"}


def get_context(context):
	if frappe.session.user == "Guest":
		frappe.local.flags.redirect_location = "/login?" + urlencode(
			{"redirect-to": frappe.request.full_path.rstrip("?")}
		)
		raise frappe.Redirect(302)

	# Legacy ERPNext links: /projects?project=PROJ-0001 → /projects/PROJ-0001
	if (legacy := frappe.form_dict.get("project")) and not frappe.form_dict.get("app_path"):
		frappe.local.flags.redirect_location = f"/projects/{quote(legacy, safe='')}"
		raise frappe.Redirect(302)

	csrf_token = frappe.sessions.get_csrf_token()
	# The token is created lazily; persist it before the page renders or the
	# SPA's first POST fails CSRF validation.
	frappe.db.commit()  # nosemgrep: frappe-manual-commit

	context.no_cache = 1
	context.boot = get_boot(csrf_token)
	return context


def get_boot(csrf_token: str | None = None) -> dict:
	user = frappe.session.user
	info = frappe.db.get_value("User", user, ["full_name", "user_image", "desk_theme"], as_dict=True) or {}
	theme = {"Dark": "dark", "Automatic": "automatic"}.get(info.get("desk_theme") or "", "light")

	portal_menu = [
		{"title": item.get("title"), "route": item.get("route"), "target": item.get("target")}
		for item in get_portal_sidebar_items()
		if item.get("route") and item.get("route") not in _OWN_ROUTES
	]

	return {
		"csrf_token": csrf_token or frappe.sessions.get_csrf_token(),
		"site_name": frappe.local.site,
		"user": user,
		"user_fullname": info.get("full_name") or user,
		"user_image": info.get("user_image") or "",
		"is_staff": is_staff(user),
		"lang": frappe.local.lang or "en",
		"theme": theme,
		"brand": {
			"logo": get_app_logo(),
			"title": frappe.get_website_settings("app_name") or frappe.get_system_settings("app_name") or "",
		},
		"portal_menu": portal_menu,
	}


@frappe.whitelist(methods=["POST"])
def get_context_for_dev() -> dict:
	"""Boot data for the Vite dev server (``yarn dev:portal``), developer mode only."""
	if not frappe.conf.developer_mode:
		frappe.throw(frappe._("This method is only meant for developer mode"))
	return get_boot()
